# -*- coding: utf-8 -*-
import sys
import numpy as np

from utils import strToBytes, bytesToStr
from Cipher import S_DES

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication


class Ui_MainWindow(object):
    def __init__(self):
        self.machine = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 771, 631))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.p1_textEdit = QtWidgets.QTextEdit(self.tab)
        self.p1_textEdit.setGeometry(QtCore.QRect(200, 83, 431, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.p1_textEdit.setFont(font)
        self.p1_textEdit.setObjectName("p1_textEdit")
        self.p1_label = QtWidgets.QLabel(self.tab)
        self.p1_label.setGeometry(QtCore.QRect(80, 103, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.p1_label.setFont(font)
        self.p1_label.setObjectName("p1_label")
        self.key1_label_2 = QtWidgets.QLabel(self.tab)
        self.key1_label_2.setGeometry(QtCore.QRect(130, 253, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.key1_label_2.setFont(font)
        self.key1_label_2.setObjectName("key1_label_2")
        self.k1_textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.k1_textEdit_2.setGeometry(QtCore.QRect(200, 263, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.k1_textEdit_2.setFont(font)
        self.k1_textEdit_2.setObjectName("k1_textEdit_2")
        self.radioButton = QtWidgets.QRadioButton(self.tab)
        self.radioButton.setGeometry(QtCore.QRect(200, 213, 115, 19))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(510, 213, 115, 19))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.c1_textEdit_3 = QtWidgets.QTextEdit(self.tab)
        self.c1_textEdit_3.setEnabled(False)
        self.c1_textEdit_3.setGeometry(QtCore.QRect(200, 363, 431, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.c1_textEdit_3.setFont(font)
        self.c1_textEdit_3.setObjectName("c1_textEdit_3")
        self.c1_label_3 = QtWidgets.QLabel(self.tab)
        self.c1_label_3.setGeometry(QtCore.QRect(70, 383, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.c1_label_3.setFont(font)
        self.c1_label_3.setObjectName("c1_label_3")
        self.e_pushButton = QtWidgets.QPushButton(self.tab)
        self.e_pushButton.setGeometry(QtCore.QRect(350, 480, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.e_pushButton.setFont(font)
        self.e_pushButton.setObjectName("e_pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(80, 103, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.c2_textEdit_4 = QtWidgets.QTextEdit(self.tab_2)
        self.c2_textEdit_4.setGeometry(QtCore.QRect(200, 83, 431, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.c2_textEdit_4.setFont(font)
        self.c2_textEdit_4.setObjectName("c2_textEdit_4")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_3.setGeometry(QtCore.QRect(200, 213, 115, 19))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(130, 253, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.d_pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.d_pushButton_2.setGeometry(QtCore.QRect(350, 480, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.d_pushButton_2.setFont(font)
        self.d_pushButton_2.setObjectName("d_pushButton_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_4.setGeometry(QtCore.QRect(510, 213, 115, 19))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.p2_textEdit_6 = QtWidgets.QTextEdit(self.tab_2)
        self.p2_textEdit_6.setEnabled(False)
        self.p2_textEdit_6.setGeometry(QtCore.QRect(200, 363, 431, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.p2_textEdit_6.setFont(font)
        self.p2_textEdit_6.setObjectName("p2_textEdit_6")
        self.k2_textEdit_5 = QtWidgets.QTextEdit(self.tab_2)
        self.k2_textEdit_5.setGeometry(QtCore.QRect(200, 263, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.k2_textEdit_5.setFont(font)
        self.k2_textEdit_5.setObjectName("k2_textEdit_5")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(70, 383, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.p3_textEdit_7 = QtWidgets.QTextEdit(self.tab_3)
        self.p3_textEdit_7.setGeometry(QtCore.QRect(200, 80, 431, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.p3_textEdit_7.setFont(font)
        self.p3_textEdit_7.setObjectName("p3_textEdit_7")
        self.c3_textEdit_8 = QtWidgets.QTextEdit(self.tab_3)
        self.c3_textEdit_8.setEnabled(True)
        self.c3_textEdit_8.setGeometry(QtCore.QRect(200, 250, 431, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.c3_textEdit_8.setFont(font)
        self.c3_textEdit_8.setObjectName("c3_textEdit_8")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(70, 270, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(80, 100, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_5.setGeometry(QtCore.QRect(510, 380, 115, 19))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_6.setGeometry(QtCore.QRect(200, 380, 115, 19))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.bf_pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.bf_pushButton_3.setGeometry(QtCore.QRect(340, 540, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.bf_pushButton_3.setFont(font)
        self.bf_pushButton_3.setObjectName("bf_pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(120, 420, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.k3_textEdit_9 = QtWidgets.QTextEdit(self.tab_3)
        self.k3_textEdit_9.setEnabled(False)
        self.k3_textEdit_9.setGeometry(QtCore.QRect(200, 430, 431, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.k3_textEdit_9.setFont(font)
        self.k3_textEdit_9.setObjectName("k3_textEdit_9")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

############################################################################################
        self.machine = S_DES()
        self.e_pushButton.clicked.connect(self.encrypt_text)  # 为加密按钮绑定点击事件
        self.d_pushButton_2.clicked.connect(self.decrypt_text)
        self.bf_pushButton_3.clicked.connect(self.bf_text)

    def encrypt_text(self):
        isBinary = None

        if self.radioButton.isChecked():
            isBinary = True

        if self.radioButton_2.isChecked():
            isBinary = False

        print(isBinary)
        # 获取输入的明文
        plain_text = self.p1_textEdit.toPlainText()
        key_text = self.k1_textEdit_2.toPlainText()  # 固定加密密钥

        print(plain_text)

        x = strToBytes(plain_text, isBinary)
        key = strToBytes(key_text, isBinary)

        c = self.machine.forward(x, key, isEncrypt=True)
        cipher_text = bytesToStr(c, isBinary)
        # 将加密后的内容显示在密文文本框中
        self.c1_textEdit_3.setPlainText(cipher_text)
        self.c1_textEdit_3.setEnabled(True)

    def decrypt_text(self):
        isBinary = None

        if self.radioButton_3.isChecked():
            isBinary = True

        if self.radioButton_4.isChecked():
            isBinary = False

        print(isBinary)
        # 获取输入的明文
        cipher_text = self.c2_textEdit_4.toPlainText()
        key_text = self.k2_textEdit_5.toPlainText()

        c = strToBytes(cipher_text, isBinary)
        key = strToBytes(key_text, isBinary)

        p = self.machine.forward(c, key, isEncrypt=False)
        plainText = bytesToStr(p, isBinary)

        self.p2_textEdit_6.setPlainText(plainText)
        self.p2_textEdit_6.setEnabled(True)

    def bf_text(self):
        isBinary = None

        if self.radioButton_6.isChecked():
            isBinary = True

        if self.radioButton_5.isChecked():
            isBinary = False
        # 获取输入的明文
        print(isBinary)
        plain_text = self.p3_textEdit_7.toPlainText()
        cipher_text = self.c3_textEdit_8.toPlainText()

        p = strToBytes(plain_text, isBinary)
        c = strToBytes(cipher_text, isBinary)

        keys, time_spend = self.machine.bruteForce(p, c)

        text = ""
        for key in keys:
            text_key = bytesToStr(key, True)
            text += text_key
            text += "\n"

        text += "time_spend: " + str(time_spend) + "ms"
        self.k3_textEdit_9.setPlainText(text)
        self.k3_textEdit_9.setEnabled(True)


#################################################################################3


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple-DES"))
        MainWindow.setWindowIcon(QtGui.QIcon("./favicon.ico"))
        self.p1_label.setText(_translate("MainWindow", "PlainText："))
        self.key1_label_2.setText(_translate("MainWindow", "Key："))
        self.k1_textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.radioButton.setText(_translate("MainWindow", "比特串"))
        self.radioButton_2.setText(_translate("MainWindow", "字符串"))
        self.c1_label_3.setText(_translate("MainWindow", "CipherText:"))
        self.e_pushButton.setText(_translate("MainWindow", "Encrypt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "加密"))
        self.label_6.setText(_translate("MainWindow", "CipherText："))
        self.radioButton_3.setText(_translate("MainWindow", "比特串"))
        self.label_5.setText(_translate("MainWindow", "Key："))
        self.d_pushButton_2.setText(_translate("MainWindow", "Decrypt"))
        self.radioButton_4.setText(_translate("MainWindow", "字符串"))
        self.k2_textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "PlainText："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "解密"))
        self.label_7.setText(_translate("MainWindow", "CipherText："))
        self.label_9.setText(_translate("MainWindow", "PlainText："))
        self.radioButton_5.setText(_translate("MainWindow", "字符串"))
        self.radioButton_6.setText(_translate("MainWindow", "比特串"))
        self.bf_pushButton_3.setText(_translate("MainWindow", "Brute Force"))
        self.label_8.setText(_translate("MainWindow", "Key："))
        self.k3_textEdit_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "破解"))




if __name__ == "__main__":
    app = QApplication(sys.argv)  # 创建一个应用程序对象
    MainWindow = QtWidgets.QMainWindow()  # 创建主窗口对象
    ui = Ui_MainWindow()  # 创建UI对象
    ui.setupUi(MainWindow)  # 设置UI界面
    MainWindow.show()  # 显示主窗口
    sys.exit(app.exec_())  # 进入应用程序的主循环